SGpp/DisCoTec

distributedcombigrid/examples/combi_example/out/l2_norm_of_difference.sh
distributedcombigrid/examples/gene_distributed/tools/Makefile
distributedcombigrid/tools/Makefile
distributedcombigrid/tools/errorCalc.cpp

I have adapted Mario's GENE checkpoint compare program to support our output format in arbitrary dimensions. Example on usage given in `distributedcombigrid/examples/combi_example/out/l2_norm_of_difference.sh`.

Error calc tool

---

distributedcombigrid/src/sgpp/distributedcombigrid/fullgrid/DistributedFullGrid.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupManager.cpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupManager.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupSignals.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupWorker.cpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupWorker.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessManager.cpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessManager.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/mpi/MPISystem.cpp
distributedcombigrid/src/sgpp/distributedcombigrid/mpi/MPITags.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/utils/MonteCarlo.hpp
distributedcombigrid/tests/test_distributedfullgrid.cpp
distributedcombigrid/tests/test_integration.cpp
distributedcombigrid/tests/test_rescheduling.cpp

allows to interpolate the combi solution on arbitrary coordinates (like for monte carlo error evaluation).

Feature component grid interpolation

---

.gitignore
distributedcombigrid/src/sgpp/distributedcombigrid/fullgrid/DistributedFullGrid.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/CombiParameters.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupManager.cpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupManager.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupSignals.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupWorker.cpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupWorker.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessManager.cpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessManager.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/mpi/MPICartesianUtils.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/sparsegrid/DistributedSparseGridUniform.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/utils/Config.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/utils/IndexVector.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/utils/LevelSetUtils.cpp
distributedcombigrid/src/sgpp/distributedcombigrid/utils/LevelSetUtils.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/utils/Stats.hpp
distributedcombigrid/tests/test_distributedfullgrid.cpp
distributedcombigrid/tests/test_distributedsparsegrid.cpp
distributedcombigrid/tests/test_helper.hpp
distributedcombigrid/tests/test_hierarchization.cpp
distributedcombigrid/tests/test_integration.cpp
distributedcombigrid/tests/test_loadmodel.cpp
distributedcombigrid/tests/test_mpisystem.cpp
distributedcombigrid/tests/test_reduce.cpp
distributedcombigrid/tests/test_rescheduling.cpp

This PR contains a lot of neat stuff I developed for the widely-distributed experiment:
- memory-optimized cartesian communicator utilities
- write/read sparse grid with MPI-IO
- optimized registration for DFGs / DSGs (from minutes or hours to seconds)
- some more unit tests, regression tests, and timing tests

Pick nice things from third level

---

distributedcombigrid/examples/distributed_advection/TaskAdvection.hpp
distributedcombigrid/examples/distributed_advection/combi_example.cpp
distributedcombigrid/src/sgpp/distributedcombigrid/fullgrid/DistributedFullGrid.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/hierarchization/DistributedHierarchization.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupWorker.cpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupWorker.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/utils/IndexVector.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/utils/LevelSetUtils.hpp
distributedcombigrid/tests/TaskConstParaboloid.hpp
distributedcombigrid/tests/TaskCount.hpp
distributedcombigrid/tests/test_distributedfullgrid.cpp
distributedcombigrid/tests/test_distributedsparsegrid.cpp
distributedcombigrid/tests/test_helper.hpp
distributedcombigrid/tests/test_hierarchization.cpp
distributedcombigrid/tests/test_integration.cpp

This PR fixes a lot of things that were not fully implemented in 
https://github.com/SGpp/DisCoTec/pull/25
yet (although there may still be more to do!)

Finalize one sided boundary

---

distributedcombigrid/src/sgpp/distributedcombigrid/hierarchization/DistributedHierarchization.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupWorker.cpp
distributedcombigrid/tests/test_hierarchization.cpp

... with tests and timing measurements!

Introduce minimum level for hierarchization and dehierarchization

---

distributedcombigrid/examples/selalib_distributed/src/selalib_distributed.cpp
distributedcombigrid/src/sgpp/distributedcombigrid/combischeme/CombiMinMaxScheme.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/hierarchization/DistributedHierarchization.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/CombiParameters.hpp
distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupWorker.cpp
distributedcombigrid/tests/test_integration.cpp
site_scons/SGppConfigure.py

Some neat things I'd like to steal from branch third-level-advection to master. 
Most importantly 71d34be96, which causes the hierarchization not to send all data with hierarchical hat functions (a bug I must have introduced some time ago).

Fix hierarchization

---

examples/distributed_advection/TaskAdvection.hpp
examples/distributed_third_level/TaskAdvection.hpp
src/CMakeLists.txt
src/fullgrid/DistributedFullGrid.hpp
src/loadmodel/AveragingLoadModel.hpp
src/rescheduler/TaskRescheduler.hpp
src/sparsegrid/DistributedSparseGridUniform.hpp
src/utils/Stats.hpp
tests/TaskConstParaboloid.hpp
tests/TaskCount.hpp
tests/test_loadmodel.cpp
tests/test_task.cpp
third_level_manager/CMakeLists.txt

to make compilable with clang (and maybe fix some undefined behaviours)

Fixes for clang

---

src/io/MPIInputOutput.hpp
src/manager/ProcessGroupWorker.cpp
tests/test_thirdLevel.cpp

effectively: 
- fix a file name bug in test_thirdLevel, and 
- re-apply a commit to avoid every process polling a token file

Fix io race condition

---

examples/distributed_advection/TaskAdvection.hpp
examples/distributed_advection/combi_example.cpp
examples/distributed_third_level/TaskAdvection.hpp
src/fullgrid/DistributedFullGrid.hpp
src/fullgrid/SliceIterator.hpp
tests/test_distributedfullgrid.cpp

slightly tensorized the AdvectionTask::run() function

Feature try less index calculations

---

src/hierarchization/DistributedHierarchization.hpp
src/manager/ProcessGroupWorker.cpp
tests/test_distributedfullgrid.cpp

avoid some vector / copy operations in distributed hierarchization

simpler hierarchization

---

examples/distributed_third_level/TaskAdvection.hpp
src/fullgrid/DistributedFullGrid.hpp
tests/test_distributedfullgrid.cpp

iterate basis functions for interpolation non-recursively
-- find neighbors by set bits in iterable instead

Unvectored interpolation iteration

---

examples/distributed_third_level/combi_example_worker_only.cpp
src/io/MPIInputOutput.hpp
src/manager/ProcessGroupWorker.cpp
src/manager/ProcessGroupWorker.hpp
tests/test_thirdLevel.cpp

MPIIO: use better(?) default parameters

---

tools/evaluate.py

Add a file to evaluate stat files which exports the evaluated metrics to CSV files.

Evaluation Script

---

examples/distributed_third_level/combi_example_worker_only.cpp
src/io/MPIInputOutput.hpp
src/manager/ProcessGroupWorker.cpp
src/sparsegrid/DistributedSparseGridUniform.hpp

* read/reduce sparse grid files at a maximum of four chunks
* other IO-things

Fix chunked readreduce

---

examples/combi_example/combi_example.cpp
examples/combi_example_faults/HelperFunctions.hpp
examples/combi_example_faults/combi_example_faults.cpp
examples/distributed_advection/combi_example.cpp
examples/distributed_advection/get_mc_variance.cpp
examples/distributed_third_level/combi_example.cpp
examples/distributed_third_level/combi_example_worker_only.cpp
examples/distributed_third_level/get_mc_variance.cpp
examples/distributed_third_level/mpimemory.cpp
examples/selalib_distributed/src/combine_selalib_diagnostics.cpp
examples/selalib_distributed/src/selalib_distributed.cpp
src/CMakeLists.txt
src/combischeme/CombiMinMaxScheme.hpp
src/io/BroadcastParameters.cpp
src/io/BroadcastParameters.hpp
src/io/MPIInputOutput.hpp
src/manager/ProcessGroupWorker.cpp
src/manager/ProcessManager.cpp
src/utils/MonteCarlo.cpp
src/utils/MonteCarlo.hpp
src/utils/Stats.cpp
src/utils/Stats.hpp
tests/test_ftolerance.cpp
tests/test_integration.cpp
tests/test_thirdLevel.cpp
tests/test_worker_only.cpp
third_level_manager/test_uftp.cpp
tools/subspace_writer/subspace_writer.cpp

Only Rank zero reads parameter files, broadcasts  to other ranks.
cf. https://github.com/SGpp/DisCoTec/issues/75

Feature: Broadcast parameters

---

examples/selalib_distributed/src/combine_selalib_diagnostics.cpp

revert d86233b for combine_selalib_diagnostics

---

examples/combi_example/combi_example.cpp
examples/combi_example_faults/combi_example_faults.cpp
examples/combi_workers_only/combi_example_worker_only.cpp
examples/distributed_advection/combi_example.cpp
examples/distributed_third_level/combi_example.cpp
examples/distributed_third_level/combi_example_worker_only.cpp
examples/selalib_distributed/src/selalib_distributed.cpp
src/CMakeLists.txt
src/combicom/CombiCom.hpp
src/manager/CombiParameters.hpp
src/manager/ProcessGroupWorker.cpp
src/manager/SparseGridWorker.hpp
src/mpi/MPISystem.cpp
src/sparsegrid/AnyDistributedSparseGrid.cpp
src/sparsegrid/AnyDistributedSparseGrid.hpp
src/sparsegrid/DistributedSparseGridUniform.hpp
src/utils/Types.hpp
tests/test_distributedsparsegrid.cpp
tests/test_helper.hpp
tests/test_integration.cpp
tests/test_thirdLevel.cpp
tests/test_worker_only.cpp
third_level_manager/test_uftp.cpp
tools/subspace_writer/subspace_writer.cpp

Feature: subspace reduce

---

examples/distributed_third_level/combi_example_worker_only.cpp
src/fullgrid/DistributedFullGrid.hpp
src/fullgrid/Tensor.hpp
src/mpi/MPICartesianUtils.hpp
src/mpi/MPISystem.cpp
src/sparsegrid/AnyDistributedSparseGrid.cpp
src/sparsegrid/AnyDistributedSparseGrid.hpp
tests/test_distributedfullgrid.cpp
tests/test_distributedsparsegrid.cpp
tests/test_hierarchization.cpp
tests/test_thirdLevel.cpp

avoid duplication in storeLocalComm and setOutgroupCommunicator ; other correctness checks and memory optimizations

Have fewer MPI comms

---

examples/distributed_third_level/combi_example_worker_only.cpp
src/io/MPIInputOutput.hpp
src/manager/ProcessGroupWorker.cpp
src/manager/SparseGridWorker.hpp
src/sparsegrid/DistributedSparseGridIO.hpp
tests/test_distributedsparsegrid.cpp
tests/test_thirdLevel.cpp
tools/subspace_writer/README.md
tools/subspace_writer/subspace_writer.cpp

* readreduce w/ parameterized chunk size
* file size checks on mpi-read
* some info hints for mpi-io

Feature chunked readreduce

---

examples/selalib_distributed/CMakeLists.txt
examples/selalib_distributed/sbatch.sh
examples/selalib_distributed/src/selalib_distributed_workers_only.cpp
src/manager/ProcessGroupWorker.cpp
src/manager/ProcessGroupWorker.hpp

all the neat features to update the experiments in https://doi.org/10.18419/darus-2784 to the most recent DisCoTec.
It's also connected to 
[this selalib PR ](https://github.com/selalib/selalib/pull/26)
and the recent changes in https://github.com/freifrauvonbleifrei/discotec-scaling-scripts .

selalib: workers only

---

.jenkins/Jenkinsfile
README.md
src/fullgrid/DistributedFullGrid.hpp
tests/test_distributedsparsegrid.cpp
tests/test_hierarchization.cpp
tests/test_thirdLevel.cpp

- add Jenkinsfile for multibranch pipeline
- set some test timeouts longer (to allow for concurrent matrix execution of different builds)

Feature jenkins pipeline

---

.jenkins/Jenkinsfile
README.md

cf. https://github.com/spack/spack/pull/35239

jenkins: use official spack repo (which now has discotec)

---

src/CMakeLists.txt
src/io/FileInputOutput.cpp
src/io/FileInputOutput.hpp
src/io/MPIInputOutput.hpp
src/utils/Stats.hpp

this is basically pr #114 , but in a branch in the discotec namespace so the CI can check it out easily.

 The statistics files are only written by the root MPI process, stolen from #114 
