SGpp/DisCoTec

distributedcombigrid/examples/combi_example/combi_example.cpp, distributedcombigrid/examples/combi_example_faults/combi_example_faults.cpp, distributedcombigrid/examples/gene_distributed/src/manager.cpp, distributedcombigrid/examples/gene_distributed_linear/src/manager.cpp, distributedcombigrid/src/sgpp/distributedcombigrid/combischeme/CombiMinMaxScheme.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/fullgrid/DistributedFullGrid.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/loadmodel/LearningLoadModel.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/CombiParameters.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupManager.cpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupManager.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupWorker.cpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupWorker.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessManager.cpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessManager.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/task/Task.cpp, distributedcombigrid/src/sgpp/distributedcombigrid/task/Task.hpp, distributedcombigrid/tests/TaskCount.hpp, distributedcombigrid/tests/test_ftolerance.cpp, distributedcombigrid/tests/test_integration.cpp, distributedcombigrid/tests/test_mpisystem.cpp, distributedcombigrid/tests/test_reduce.cpp, distributedcombigrid/tests/test_rescheduling.cpp, distributedcombigrid/tests/test_scheme.json, distributedcombigrid/tools/generate_combischeme_json.py, test_scheme.json
DisCoTec should be ready for some absurdly large widely distributed runs, so I put a few features to be merged into master:
- pass in custom decompositions (the default decomposition works only for power-of-two process counts `p`)
- have `Task`'s ID be `size_t`s -- in case we want some reaaaally large task counts
- have some functionality to read combination schemes from json files (plus which process group tasks should be run on, so we can have a static task assignment)
- some script to generate such json scheme files (still missing)
=> Ready for Terascale

SConstruct, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupManager.cpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupManager.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupSignals.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupWorker.cpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupWorker.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessManager.cpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessManager.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/sparsegrid/DistributedSparseGridUniform.hpp, distributedcombigrid/tests/TaskCount.hpp, distributedcombigrid/tests/test_distributedsparsegrid.cpp, distributedcombigrid/tests/test_hierarchization.cpp, distributedcombigrid/tests/test_integration.cpp, site_scons/ModuleHelper.py, site_scons/SGppConfigure.py
Introduces functions to:
* read and write sparse grid data chunks as binary files
* write HDF5 files of interpolated data (put `USE_HDF5` flag into scons call; requires HighFive to be installed, e.g. via spack)
=> Feature interpolation output

distributedcombigrid/examples/combi_example/TaskExample.hpp, distributedcombigrid/examples/combi_example_faults/TaskExample.hpp, distributedcombigrid/examples/gene_distributed/src/GeneTask.cpp, distributedcombigrid/examples/gene_distributed_linear/src/GeneTask.cpp, distributedcombigrid/tests/test_ftolerance.cpp
(especially in decideToKill())
-- and replace them by `theMPISystem` interface calls
=> Task implementations: avoid calls to MPI_Comm_rank

distributedcombigrid/src/sgpp/distributedcombigrid/combischeme/CombiMinMaxScheme.cpp, distributedcombigrid/src/sgpp/distributedcombigrid/combischeme/CombiMinMaxScheme.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/sparsegrid/DistributedSparseGrid.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/sparsegrid/DistributedSparseGridUniform.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/sparsegrid/SGrid.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/utils/LevelVector.cpp, distributedcombigrid/src/sgpp/distributedcombigrid/utils/LevelVector.hpp, distributedcombigrid/tests/test_distributedsparsegrid.cpp, distributedcombigrid/tests/test_ftolerance.cpp, distributedcombigrid/tests/test_reduce.cpp, distributedcombigrid/tests/test_stats.cpp
So until now, when we had a truncated combi scheme with dimension > 2, like lmin = [3, 3, 3], lmax=[7, 7, 7], then there would be loads of unnecessary level vectors: for instance, [7, 5, 1] would be included in the scheme. It becomes severe if you go to high dimensions and resolutions, and/or want to use the reduced level vector trick (to avoid communication of the finest resolved hierarchical subspaces).
This was due to mixed dimension level sums not being checked (only single dimensions and the whole level vector sum was restricted). 
This PR puts the functionality into LevelVector.cpp and fixes the issue: `combigrid::createTruncatedHierarchicalLevels` and `combigrid::createTruncatedHierarchicalLevelsRec`. The function is called from the Sparse Grid implementations.
Also, there are more …
=> Fix hierarchical index set

distributedcombigrid/src/sgpp/distributedcombigrid/fullgrid/DistributedFullGrid.hpp, distributedcombigrid/src/sgpp/distributedcombigrid/manager/ProcessGroupWorker.cpp, distributedcombigrid/src/sgpp/distributedcombigrid/sparsegrid/DistributedSparseGridUniform.hpp, distributedcombigrid/tests/test_distributedfullgrid.cpp, distributedcombigrid/tests/test_distributedsparsegrid.cpp, distributedcombigrid/tests/test_hierarchization.cpp
This PR has two things:
first, we don't store the connection between the sparse and full grid DOF any more but compute them ad hoc. for the timings in test_registerUniformSG, this means that the time to register is almost zero now (because no vectors are stored), but the timings for adding and extracting are higher (approx. 0.7-2s on ipvs-epyc1).
second, the register and add functions are moved from the class DistributedFullGrid to DistributedSparseGridUniform, to make more explicit which structure is and isn't changed.
also, some of the tests were not doing what one would expect, which I have changed.
=> Feature full grid sparse grid mapping

src/io/MPIInputOutput.hpp
The buffer 'pos' is of fixed type MPI_Offset, so use the predefined MPI datatype MPI_OFFSET.
=> Fix MPI datatype for MPI_Offset

src/io/MPIInputOutput.hpp
MPI_File_open may fail due to multiple problems and not return MPI_SUCCESS.
So check for MPI_ERR_FILE_EXISTS if you intend to check for file existence.
=> Correct check for file existence to use MPI_ERR_FILE_EXISTS

src/fullgrid/DistributedFullGrid.hpp
Replace deprecated std::bind1st with std::bind.
=> Fix compiler warning about deprecated std::bind1st

src/mpi/MPIMemory.cpp
MPI_Allreduce is an expensive operation. Therefore, merge consecutive MPI_Allreduce operations by combining single elements into a multi element buffer and extract the results afterwards.
=> Merge consecutive MPI_Allreduce operations into one

examples/distributed_third_level/combi_example_worker_only.cpp, src/combicom/CombiCom.hpp, src/manager/ProcessGroupWorker.cpp, src/manager/ProcessGroupWorker.hpp, tests/test_worker_only.cpp
third level distributed advection with only workers:
- Use MPI_Reduce instead of MPI_Allreduce in "global reduce" operation in combination
- adds another run+interpolate at end of time loop
=> Feature true global reduce

third_level_manager/copy_file_from_hawk_to_ng.sh, third_level_manager/copy_file_from_ng_to_hawk.sh
To start off with: This fix is based on the UFTP documentation and was not tested by myself. Please test before merging.
The transfer with multiple uftp processes should not copy the same data multiple times. Therefore use uftp's byte range option (-B) to specify the parts each process should transfer. Use the "-p" flag to only write the specific range.
See the uftp-client documentation for more details: https://uftp-docs.readthedocs.io/en/latest/user-docs/uftp-client/manual.html#byte-ranges
=> Fix UFTP transfer with multiple uftp processes

src/fullgrid/DistributedFullGrid.hpp
The MPI 4.0 standard (p.646) specifies that access modes are 'a bit vector OR'. So do not rely on sum to work.
=> Fix MPI file access modes that should be combined with bit vector OR

src/combicom/CombiCom.hpp, src/manager/ProcessGroupWorker.cpp, src/manager/SparseGridWorker.hpp, tests/test_thirdLevel.cpp
For some setups, we would get MPI_Allreduce truncation errors (but weirdly, not for the weak scaling setup).
Here is a fix along with a few more sanity checks.
PS: errors like
```
Abort(203042319) on node 4092 (rank 4092 in comm 0): Fatal error in PMPI_Wait: Other MPI error, error stack:
PMPI_Wait(205)..................: MPI_Wait(request=0x7ffd5b0155cc, status=0x1) failed
MPIR_Wait(105)..................: 
MPIDU_Sched_progress_state(1036): Invalid communicator
```
can be attributed to a "wrong" default of I_MPI_ADJUST_IBCAST that does not allow for non-power-of-two numbers of groups. parameters that worked for us (on IntelMPI 2019.12) were 1 and 4
=> Fix allreduce error

src/sparsegrid/AnyDistributedSparseGrid.cpp
have a single (but hard-coded) place to change the maximum number of groups for subspace and outgroup reduce, as determined by the length of the datatype used.
=> Subspace vote for more groups

examples/distributed_third_level/combi_example_worker_only.cpp, src/combischeme/CombiMinMaxScheme.hpp, src/combischeme/CombiThirdLevelScheme.cpp, src/combischeme/CombiThirdLevelScheme.hpp, src/io/FileInputOutput.cpp, src/io/FileInputOutput.hpp, src/io/MPIInputOutput.hpp, src/manager/ProcessGroupManager.cpp, src/manager/ProcessGroupManager.hpp, src/manager/ProcessGroupWorker.cpp, src/manager/ProcessGroupWorker.hpp, src/manager/ProcessManager.hpp, src/manager/SparseGridWorker.hpp, src/sparsegrid/DistributedSparseGridIO.hpp, tests/test_thirdLevel.cpp, tests/test_worker_only.cpp, tools/subspace_writer/subspace_writer.cpp
This PR adapts the functions for file-based combination for three systems 
(where easily possible, for arbitrary numbers of systems).
It is assumed that Outgroup Sparse Grid Reduce is used for the widely-distributed combination (so each system has to write only one file, which is then copied to all other systems).
=> three systems for file-based widely-distributed combination

src/mpi_fault_simulator/MPI-FT.h
ULFM is starting to be part of major MPI releases, which needs some adaptation in the current fault simulator implementation.
=> Update fault tolerance

tests/test_ftolerance.cpp
the newer boost versions don't resolve `boost::numeric_cast` used in tests anymore. replaced by `static_cast`.
=> Fix missing boost include

.jenkins/Jenkinsfile
Apparently, the `spack load --only dependencies` command has been deprecated. Trying to explicitly load all run dependencies instead.
=> Jenkinsfile: update spack syntax

paper.md
A few small suggestions, which accompany my review of the JOSS draft manuscript.
=> [JOSS] Minor editorial revisions

.jenkins/Jenkinsfile, examples/selalib_distributed/postprocessing/combine_selalib_phi.cpp, examples/selalib_distributed/template/param.nml
Fixes an error that occured with `spack dev-build discotec+selalib`, where `combine_selalib_phi` could not be built.
I tried to put the selalib build into the CI, but weird spack dependency problems keep HDF5 from building, so I reverted that.
=> Fix selalib build error

.jenkins/Jenkinsfile
to make CI run again by fixing spack version
=> Jenkins: steal working changes from other branch
